import { Book } from "../../../../types/global";

export const books: Book[] = [
  {
    id: 'spinoza-ethique',
    title: 'Éthique',
    author: 'Spinoza',
    color: '#6B4423',
    height: 92,
    width: 38,
    quote: 'La béatitude n\'est pas le prix de la vertu, mais la vertu même.',
  },
  {
    id: 'carrere-refuge',
    title: 'Le Refuge',
    author: 'Carrère',
    color: '#8B5A3C',
    height: 78,
    width: 36,
  },
  {
    id: 'camus-etranger',
    title: "L'Étranger",
    author: 'Camus',
    color: '#1F2A44',
    height: 95,
    width: 34,
  },
  {
    id: 'aurele-meditations',
    title: 'Méditations',
    author: 'Aurèle',
    color: '#A8895C',
    textColor: '#1a1a1a',
    height: 70,
    width: 40,
  },
  {
    id: 'thoreau-walden',
    title: 'Walden',
    author: 'Thoreau',
    color: '#2D4A3E',
    height: 100,
    width: 36,
  },
  {
    id: 'descartes-discours',
    title: 'Discours',
    author: 'Descartes',
    color: '#7A2E2E',
    height: 65,
    width: 32,
  },
  {
    id: 'platon-banquet',
    title: 'Le Banquet',
    author: 'Platon',
    color: '#D4A574',
    textColor: '#1a1a1a',
    height: 82,
    width: 42,
  },
  {
    id: 'proust-cote',
    title: 'Du Côté',
    author: 'Proust',
    color: '#2A2D5C',
    height: 75,
    width: 34,
  },
  {
    id: 'dostoievski-idiot',
    title: "L'Idiot",
    author: 'Dostoïevski',
    color: '#8B2E2E',
    height: 88,
    width: 38,
  },
]